paths:
  dataset: "dataset.csv"
  checkpoint: "checkpoint.pth"
  input: "input.yaml"
  checkpoint_key: "checkpoint.key"

training:
  trainMode: False
  epochs: 1000
  patience: 20
  learning_rate: 0.0005

device: "cpu"
